### ISSUE TITLE
About set function

### ISSUE THREAD

**Issue by maxtrunk** [thephpleague/monga#17]
I notice the set function is updated. But I am wondering why remove the default value of the second parameter. If user pass in an array, they have to pass a value for second parameter even it are used.
 
public function set($field, $value)
{
if (! is_array($field)) {
$field = array($field => $value);
}
foreach ($field as $f => $v) {
$this->update('$set', $f, $v);
}
return $this;
}

**Comment by bcrowe** [comment]
Nice find. Thanks. Fixed in https://github.com/thephpleague/monga/commit/787baf90c110e8d364095fcae9e384a9534b4233.
