### ISSUE TITLE
Seeder

### ISSUE THREAD

**Issue by webkenny** [thephpleague/monga#22]
Love this library so far but I have a need to do some random seeding of data for an API I am putting together. Is there a recommended approach to do that with `monga` or would it be worth my rolling a plugin for `fzaninotto/Faker`?

**Comment by bcrowe** [comment]
Personally, I normally end up making a shell and using fzaninotto/Faker to generate some dummy data. This library is focused around Mongo operations themselves. Seems like you got the right idea.

**Comment by webkenny** [comment]
Brilliant. Thanks for the support.
