### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by webkenny** [thephpleague/monga#24]
Is there published documentation for this library? I'm having a hell of a time figuring out some basic things like, for example, using an operator other than the `=` sign in a query. i.e. Find all items in a collection where the timestamp is less than now.

Anyway are there docs or am I going rogue code diving?

(Great library, so far! Thanks for putting this out there)

**Comment by webkenny** [comment]
Pretty sure I solved this digging into the code. In my example, `$query->whereLt("field", "value")` looks like it will provide values where the field entry is less than the value specified.

**Comment by bcrowe** [comment]
The documentation is limited to what is in the README and in the gh-pages branch (incomplete). I've been meaning to finish up the gh-pages docs for a few months now, but this serves as a nice reminder. That being say, were there any other places other than operators you had trouble with?

**Comment by webkenny** [comment]
Thanks for getting back to me. I guess only one other question I would have (and I am more than happy to help write docs as I learn - FWIW) is let's say I want to pass an argument into the find method. Would this be the appropriate way or is this a case for `func_get_args()`?

```    
$results = $collection->find(function ($query, $uid) {
        $query->whereLt('timestamp', time())
          ->where('read', false)
          ->where('uid', $uid);
    });
```

Thanks for your help. Really enjoying the syntactical sugar in this lib.

**Comment by bcrowe** [comment]
You can use the `use` keyword to pass variables into the closure's scope.

```
$results = $collection->find(function ($query) use ($uid) {
        $query->whereLt('timestamp', time())
          ->where('read', false)
          ->where('uid', $uid);
    });
```

**Comment by webkenny** [comment]
You rock, sir. Thanks for taking the time and being so responsive. I'll be sure to pay you back with code as I get a little more comfortable with the tool. :+1:
