### ISSUE TITLE
Multiple remove (not issue)

### ISSUE THREAD

**Issue by rhnkyr** [thephpleague/monga#31]
I want to remove every document which have same id. My code is

```
$comments = $this->mongo->collection(Collections::COMMENTS);
        $comments->find(function ($query) use ($check) {
            $query->where('cid', $check)->remove()->multiple();
        });
```

is this type of use correct? Thanks in advance...

**Comment by bcrowe** [comment]
Check out the [Delete section of the gh-pages](https://github.com/thephpleague/monga/blob/gh-pages/crud.md#delete).

**Comment by rhnkyr** [comment]
@bcrowe thanks. Does it handle multiple delete?
