### ISSUE TITLE
Weird syntax for calling method

### ISSUE THREAD

**Issue by ftassi** [thephpleague/monga#34]
I'm having hard time figuring out why this 
```
public function andWhereNot($field, $value)
{
    return call_user_func_array([$this, 'whereNot'], func_get_args());
}
```

has been used instead of
```
public function andWhereNot($field, $value)
{
    return $this->whereNot($field, $value);
}
```

which would have been, imho, way more explicit and readable. Is there any particular reason? I'd be willing to refactor all the call_user_func_* usage to direct method calls (of course when it make sense) if you guys will accept a PR for this.

**Comment by bcrowe** [comment]
Makes sense to me. Feel free to open up a PR.

**Comment by bcrowe** [comment]
Updated in https://github.com/thephpleague/monga/commit/dd4d5b4348a7289e47cc6d23c0500d51a06192aa
